### ISSUE TITLE
Bounty for docker image?

### ISSUE THREAD

**Issue by caffo** [mrmps/SMRY#1]
@mrmps  I want to self host it in my zimaboard, can I pay you to create a docker image of it?

**Comment by mrmps** [comment]
Maybe, what would the bounty be?

**Comment by caffo** [comment]
How much do you think it is worth? Let me know your opinion.

**Comment by FireMasterK** [comment]
I'm interested in self-hosting SMRY via docker too, and will submit a PR later. I don't mind collecting a bounty if there is one. :sweat_smile:

**Comment by mrmps** [comment]
> How about $25?

Does the docker file work? Marking this issue as closed, please coordinate for the bounty

**Comment by caffo** [comment]
@mrmps will test it out and reach out to @FireMasterK after it. thanks!
